[Main]
library=0
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=0
ProjectTab=1
InformHeight=50
EntryPointList=
Title=New_Project
Config=
ExtPrg=
Message=
Romid=200
Slot=0
Emu48Ram=C:\Users\GTX 1660S\Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files (x86)\Hewlett-Packard\Debug4x\Emu\default 48GX.bin
Emu49Ram=C:\Users\GTX 1660S\Documents\Debug4x\callculadorabonita.e49
FilePath=SenCos.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=sen-cos.s
